mecanum:
  #Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  gazebo_ros_control:
   pid_gains:
      # joint_1: {p: 100.0, i: 1.0, d: 1.0}
      # joint_2: {p: 100.0, i: 1.0, d: 1.0}
      # joint_3: {p: 100.0, i: 1.0, d: 1.0}
      # joint_4: {p: 100.0, i: 1.0, d: 1.0}
      # joint_5: {p: 100.0, i: 1.0, d: 1.0}
      # joint_6: {p: 100.0, i: 1.0, d: 1.0}
      front_L_wheel_joint: {p: 30.0, i: 1.0, d: 10.0}
      front_R_wheel_joint: {p: 30.0, i: 1.0, d: 10.0}
      back_L_wheel_joint: {p: 30.0, i: 1.0, d: 10.0}
      back_R_wheel_joint: {p: 30.0, i: 1.0, d: 10.0}
      # finger_R_joint: {p: 60.0, i: 0.1, d: 10.0}
      # finger_L_joint: {p: 60.0, i: 0.1, d: 10.0}
      ## front_L_roller
      # front_L_roller_joint_1: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_2: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_3: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_4: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_5: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_6: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_7: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_8: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_9: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_10: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_11: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_12: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_13: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_14: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_15: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_16: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_17: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_18: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_19: {p: 10.0, i: 1.0, d: 0.01}
      # front_L_roller_joint_20: {p: 10.0, i: 1.0, d: 0.01}
      ## back_L_roller
      # back_L_roller_joint_1: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_2: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_3: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_4: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_5: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_6: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_7: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_8: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_9: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_10: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_11: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_12: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_13: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_14: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_15: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_16: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_17: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_18: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_19: {p: 10.0, i: 1.0, d: 0.01}
      # back_L_roller_joint_20: {p: 10.0, i: 1.0, d: 0.01}
      ## front_R_roller
      # front_R_roller_joint_1: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_2: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_3: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_4: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_5: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_6: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_7: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_8: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_9: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_10: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_11: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_12: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_13: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_14: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_15: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_16: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_17: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_18: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_19: {p: 10.0, i: 1.0, d: 0.01}
      # front_R_roller_joint_20: {p: 10.0, i: 1.0, d: 0.01}
      ## back_R_roller
      # back_R_roller_joint_1: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_2: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_3: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_4: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_5: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_6: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_7: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_8: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_9: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_10: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_11: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_12: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_13: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_14: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_15: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_16: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_17: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_18: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_19: {p: 10.0, i: 1.0, d: 0.01}
      # back_R_roller_joint_20: {p: 10.0, i: 1.0, d: 0.01}
    
